### ISSUE TITLE
Master broken?

### ISSUE THREAD

**Issue by mvukov** [acado/acado#139]
Commit c7f1361 screwed up the master?

**Comment by mvukov** [comment]
@ferreau ?

**Comment by mvukov** [comment]
```
Conflicts:
	CMakeLists.txt
	acado/bindings/acado_qpoases/qp_solver_qpoases.hpp
	examples/CMakeLists.txt
	external_packages/qpOASES-3.1.0/CMakeLists.txt
	interfaces/matlab/shared/objects.m
```

**Comment by ferreau** [comment]
Please revert this commit, I would not know how to do without creating even more mess. Sorry for that.

**Comment by mvukov** [comment]
I am on vacation, @rienq might take care about this issue.

**Comment by rienq** [comment]
I have no clue what happened here and the fix I found online did not do exactly what I hoped it would do in this case, but I have the impression the files are back to what they were before Joachim's commits.. I will leave this issue open for now though.

We also have to find a better way of pushing Joachim's fixes: @ferreau, I guess you should locally try to merge the acado master (instead of your own master) with your fixes and then push that merged version. I have the impression that your additions of the new versions of qpOASES were performed over a very old version of ACADO which created all the conflicts later on.

**Comment by ghorn** [comment]
This could be prevented in the future if people submit pull requests instead of just pushing to master. Travis-ci would have said "this pull request breaks things".
