### ISSUE TITLE
Error building model in Simulink for Quanser 3DOF Helicopter system

### ISSUE THREAD

**Issue by mohit004** [acado/acado#175]
Hi,

Actually, I have designed an NMPC for 3 DOF Quanser Helicopter system using its nonlinear model. In simulation, my code works with both 'm-file' and 's-function' (Simulink). I use the exported code, developed using codegen, for building s-function (as also done in crane example) and as I said everything works in simulation. When I design the same algorithm for the real system and use Simulink's model builder to compile the model before I can run it on the real system, I am getting certain  errors. the error stack is:

### Building q_heli3d_LQR_NMPC_new: .\q_heli3d_LQR_NMPC_new.bat
Microsoft (R) Program Maintenance Utility Version 12.00.21005.1 
Copyright (C) Microsoft Corporation.  All rights reserved. 
 
### Compiling q_heli3d_LQR_NMPC_new.cpp 
	cl  -Ox -DNDEBUG -DON_TARGET_WAIT_FOR_START=0 -DEXT_MODE -DMODEL_URI="shmem://q_heli3d_LQR_NMPC_new:1" -DVERBOSE  -DUSE_RTMODEL /wd4100 -DMODEL=q_heli3d_LQR_NMPC_new -DRT -DNUMST=2  -DTID01EQ=1 -DNCSTATES=6  -DMULTITASKING=0 -DHAVESTDIO  -DVXWORKS -DQUARC -DTARGET_TYPE=win64  -D_CRT_SECURE_NO_DEPRECATE -DASSERTIONS=1 -DDOASSERTS  -DMULTI_INSTANCE_CODE=0  -DNDEBUG   -c -DCRTAPI1=_cdecl -DCRTAPI2=_cdecl -nologo -GS -D_AMD64_=1 -DWIN64 -D_WIN64  -DWIN32 -D_WIN32 -W3 -D_WINNT -D_WIN32_WINNT=0x0502 -DNTDDI_VERSION=0x05020000 -D_WIN32_IE=0x0600 -DWINVER=0x0502 -D_MT -D_DLL -MD /wd4996 /EHsc- q_heli3d_LQR_NMPC_new.cpp
q_heli3d_LQR_NMPC_new.cpp
**c:\users\research\desktop\mohit\acado-master\interfaces\matlab\examples\code_generation\nmpc\quanser_helicopter\q_heli3d_lqr_nmpc_new_quarc_win64\q_heli3d_LQR_NMPC_new_types.h(31) : error C2371: 'acadodata' : redefinition; different basic types 
        ..\acado_solver_sfunction.h(80) : see declaration of 'acadodata' 
c:\users\research\desktop\mohit\acado-master\interfaces\matlab\examples\code_generation\nmpc\quanser_helicopter\q_heli3d_lqr_nmpc_new_quarc_win64\q_heli3d_LQR_NMPC_new_types.h(44) : error C2371: 'acadooutput' : redefinition; different basic types 
        ..\acado_solver_sfunction.h(100) : see declaration of 'acadooutput' 
c:\users\research\desktop\mohit\acado-master\interfaces\matlab\examples\code_generation\nmpc\quanser_helicopter\q_heli3d_lqr_nmpc_new_quarc_win64\q_heli3d_LQR_NMPC_new_types.h(56) : error C2371: 'acadoinput' : redefinition; different basic types 
        ..\acado_solver_sfunction.h(89) : see declaration of 'acadoinput' 
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\x86_amd64\cl.EXE"' : return code '0x2' 
Stop.

 Error(s) encountered while building model "q_heli3d_LQR_NMPC_new"
Component: Simulink | Category: Model error**

Currently I am using 'Microsoft Visual Studio 2013' to compile the code, which I am sure works as it is able to create the 's-functions' that I use in Simulations.
For the real-system (Quanser 3DOF Helicopter) there is a commercial matlab toolbox (Quarc 2.5) that I use in order to communicate with the board. I have double checked that there is no compatibility issue with this toolbox as I recently updated it and it is compatible with VS2013 for Matlab version R2014a.

I hope I could be specific enough to be understood. Please inform me if you need any other detail.
I have been struggling with this problem for the last 3 weeks. Any help by @mvukov, @rienq would be Greatly Appreciated.

Thank you
Mohit

**Comment by rienq** [comment]
Hey Mohit,

I have to tell you, the issue tracker is not the right place for this post since your request is not about a feature in the ACADO (code generation) tool itself but rather in how to use it further in your project.
You therefore should have made this post in our discussion forum which you can find here:
https://sourceforge.net/p/acado/discussion/general/

This said, you should look at the error messages which you got back from the compiler:

**c:\users\research\desktop\mohit\acado-master\interfaces\matlab\examples\code_generation\nmpc\quanser_helicopter\q_heli3d_lqr_nmpc_new_quarc_win64\q_heli3d_LQR_NMPC_new_types.h(31) : error C2371: 'acadodata' : redefinition; different basic types 
..\acado_solver_sfunction.h(80) : see declaration of 'acadodata' 
c:\users\research\desktop\mohit\acado-master\interfaces\matlab\examples\code_generation\nmpc\quanser_helicopter\q_heli3d_lqr_nmpc_new_quarc_win64\q_heli3d_LQR_NMPC_new_types.h(44) : error C2371: 'acadooutput' : redefinition; different basic types 
..\acado_solver_sfunction.h(100) : see declaration of 'acadooutput' 
c:\users\research\desktop\mohit\acado-master\interfaces\matlab\examples\code_generation\nmpc\quanser_helicopter\q_heli3d_lqr_nmpc_new_quarc_win64\q_heli3d_LQR_NMPC_new_types.h(56) : error C2371: 'acadoinput' : redefinition; different basic types 
..\acado_solver_sfunction.h(89) : see declaration of 'acadoinput' 

To me, it seems like you are trying to compile together different ACADO generated codes and there seems to be a conflict because the types "acadodata", "acadooutput" and "acadoinput" (which you can find in 'acado_solver_sfunction.h') get redefined at the moment.

Best,
Rien
